### ISSUE TITLE
Add "Added Apps" Empty List

### ISSUE THREAD

**Issue by austinarchibald** [kjwamlex/SpatialDock#2]
Wanted to add some apps other than system apps, but the list is empty? Can I add my installed apps from the Manage Apps section, but how do I do so when it asks for a URL instead of showing a list of all my installed apps to select.

**Comment by kjwamlex** [comment]
You should use the URL scheme for each app. For example, Maps app uses maps:// as URL scheme to be opened.

**Comment by austinarchibald** [comment]
How do I discover the URL scheme of my installed apps? e.g. I installed the borderless web browser [Nexus+](https://apps.apple.com/us/app/nexus/id6475538023) and use it often. How would I find the URL scheme of it and any app? Thanks!

**Comment by kjwamlex** [comment]
Usually URL schemes are found inside app's Info.plist. However, if you are unable to do that, you can make a shortcut that opens your app and add shortcut instead.

**Comment by austinarchibald** [comment]
Ok, thanks!
